export const TEAM = {
  name: "Assassins of The Void",        // ← change team name here, updates everywhere
  tagline: "We strike from what you cannot see.",
  tourGoal: 50000,              // total savings goal in ৳
  tourDate: "2027-01-01",       // target tour date
  currency: "৳",
  adminEmail: "adidkanzo@gmail.com", // ← you can make this anything

  members: [
    {
      id: "member1",
      name: "Xanin Kaizo",
      role: "Web Developer",
      status: "student",
      statusDetail: "Self-learning @ XANIN XZ",
      location: "Savar, Dhaka",
      email: "yousufx76@gmail.com",
      whatsapp: "+8801607314762",
      facebook: "https://www.facebook.com/xanin.kaizo",
      instagram: "https://www.instagram.com/xaninkaizo/",
      github: "https://github.com/yousufx76",
      avatar: "/avatars/kaizo.jpg",
      coverImage: "/covers/cover1.jpg",
      bio: "A self-taught web developer and creative from Dhaka. Passionate about design, anime, and building things that matter.",
      skills: ["Web Development", "Video Editing", "Graphic Design", "Figma"],
      hobbies: ["🎮 Gaming", "✈️ Traveling", "🎨 Art", "🎧 Music"],
      verified: true,
      genshinUID: "1807928981",        // their Genshin UID
      akashaURL: "https://akasha.cv/profile/1807928981",  // their akasha.cv profile link
    },
    {
      id: "member_2",
      name: "Seyam Alpha",
      nickname: "Seyam Alpha",
      role: "Head of the Assassin's",
      status: "student",
      statusDetail: "Central Mosque Jamia Muhammadia Arabia Madrasa Complex",
      location: "Dhaka",
      email: "eliteseyam6@gmail.com",
      whatsapp: "01717638806",
      facebook: "https://www.facebook.com/seyam.alpha",
      instagram: "",
      github: "",
      avatar: "https://res.cloudinary.com/dxtffxa1r/image/upload/v1776875886/qaxyq0ospfjej8aqt7io.jpg",
      coverImage: "/covers/covarforalpha.jpg",
      bio: "We work in the dark to serve you the light, we are Assassins of The Void\nAnime Lover, Genshin Impact player, Singal, Member of Dark Hero's.\nLove to Speak in English.\nAlmost end of my study journey.",
      skills: ["Speaking in English", "Try to act like MC", "Love to kill"],
      hobbies: ["Gaming", "Exploring my country", "Going to Anime event's"],
      genshinUID: "1810342183",
      akashaURL: "https://akasha.cv/profile/1810342183",
      verified: true,
    },
    {
      id: "member_3",
      name: "Cbr milon",
      nickname: "Cbr milon",
      role: "Photographer",
      status: "student",
      statusDetail: "Baitul mamur madrasha",
      location: "Dhaka Mirpur 11",
      email: "cbrmilon@gmail.com",
      whatsapp: "01611948912",
      facebook: "https://www.facebook.com/md.abdullah.680161",
      instagram: "https://www.instagram.com/cbrmilon/",
      github: "",
      avatar: "/avatars/abdullah.png",
      coverImage: "https://res.cloudinary.com/dxtffxa1r/image/upload/v1776913271/evhltqmdrox4bptpx4iw.jpg",
      bio: "Just figuring things out, one step at a time.Creating my own path.",
      skills: ["Gaming"],
      hobbies: ["Gaming"],
      genshinUID: "1813578112",
      akashaURL: "https://akasha.cv/profile/1813578112",
      verified: true,
    },
    {
      id: "member4",
      name: "Kenzo Mahim",
      role: "Silent Observer",
      status: "student",
      statusDetail: "Surviving life, one day at a time",
      location: "Dhaka, Bangladesh",
      email: "adidkenzo@gmail.com",
      whatsapp: "+8801619825126",
      facebook: "https://www.facebook.com/profile.php?id=61563671940329",
      instagram: "https://www.instagram.com/davy.kenzo.2024/",
      github: "",
      avatar: "/avatars/kenzo.jpg",
      coverImage: "/covers/covarforadmin.jpg",
      bio: "Man of few words, sigma of many thoughts. Doesn't care about social media but somehow ended up on this website. Loves nature, captures moments nobody else notices, and disappears before anyone asks questions. 🌿📷",
      skills: ["Photography", "Videography", "Nature Spotting", "Being Mysterious"],
      hobbies: ["📷 Photography", "🌿 Nature Walks", "🎮 Gaming", "🎧 Chilling"],
      verified: true,
      genshinUID: "1813678868",
      akashaURL: "https://akasha.cv/profile/1813678868",
    },
    {
      id: "member5",
      name: "Pir",
      role: "Squad Member",
      status: "student",
      statusDetail: "Currently in exams 📚",
      location: "Bangladesh",
      email: "",
      whatsapp: "",
      facebook: "",
      instagram: "",
      github: "",
      avatar: "/avatars/pir.jpg",
      coverImage: "/covers/coavrforpir.jpg",
      bio: "The mysterious 5th member. Currently locked in exam mode. Will reveal himself when the time is right. 🕵️",
      skills: ["Surviving Exams"],
      hobbies: ["📚 Studying (forced)"],
      verified: false,
      genshinUID: "",
      akashaURL: "",
    },


  ],

  // The member who holds the savings account
  savingsHolder: "member1",
};